apiVersion: v2
name: open5gs-5g-sa
description: Un Wrapper Chart para desplegar Open5GS SA con ArgoCD
type: application
version: 1.0.0
appVersion: "2.7.0"
dependencies:
  - name: open5gs
    version: 2.2.5
    repository: "oci://registry-1.docker.io/gradiant"
