# values.yaml CORREGIDO PARA WRAPPER CHART

# LLAVE MAESTRA: Esto le dice a Helm que configure la dependencia 'open5gs'
open5gs:
  # 1. Desactivar 4G
  mme:
    enabled: false
  hss:
    enabled: false
  sgwc:
    enabled: false
  sgwu:
    enabled: false

  # 2. PCRF Encendido
  pcrf:
    enabled: true

# 3. WEBUI ENCENDIDA (Intento de reparaci√≥n con Chart 2.5.0)
  webui:
    enabled: true
    
  # 4. Base de Datos (Latest)
  mongodb:
    image:
      tag: "latest"
    persistence:
      enabled: false
    arbiter:
      enabled: false

  # 5. Networking UPF
  upf:
    ip_forwarding: true

  # 6. Global
  global:
    image:
      pullPolicy: IfNotPresent
