# values.yaml (Vendored & Fixed)
# Nota: Al ser código directo, las variables van en la raíz.

mme:
  enabled: false
hss:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

pcrf:
  enabled: true

webui:
  enabled: true

mongodb:
  image:
    tag: "latest"
  persistence:
    enabled: false
  arbiter:
    enabled: false

upf:
  ip_forwarding: true

global:
  image:
    pullPolicy: IfNotPresent
